export const ASC_SORT_ORDER = 'asc';
export const DESC_SORT_ORDER = 'desc';
export const SORT_ORDERS_LIST = [ASC_SORT_ORDER, DESC_SORT_ORDER];

export const CONFIRM_CELL_CHANGES = 'CONFIRM_CELL_CHANGES';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
export const RESET_FILTERS = 'RESET_FILTERS';
export const RESET_SORTING = 'RESET_SORTING';