export const ITEM_MODEL = Object.seal({
    "name": "Name",
    "height": "Height",
    "mass": "Mass",
    "hair_color": "Hair color",
    "skin_color": "Skin color",
    "eye_color": "Eye color",
    "birth_year": "Birth year",
    "gender": "Gender"
});

export const ITEM_LIST = [
    {
        "name": "Luke Skywalker",
        "height": "172",
        "mass": "77",
        "hair_color": "blond",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "19BBY",
        "gender": "male",
    }, {
        "name": "C-3PO",
        "height": "167",
        "mass": "75",
        "hair_color": "n/a",
        "skin_color": "gold",
        "eye_color": "yellow",
        "birth_year": "112BBY",
        "gender": "n/a",
    }, {
        "name": "R2-D2",
        "height": "96",
        "mass": "32",
        "hair_color": "n/a",
        "skin_color": "white, blue",
        "eye_color": "red",
        "birth_year": "33BBY",
        "gender": "n/a",
    }, {
        "name": "Darth Vader",
        "height": "202",
        "mass": "136",
        "hair_color": "none",
        "skin_color": "white",
        "eye_color": "yellow",
        "birth_year": "41.9BBY",
        "gender": "male",
    }, {
        "name": "Leia Organa",
        "height": "150",
        "mass": "49",
        "hair_color": "brown",
        "skin_color": "light",
        "eye_color": "brown",
        "birth_year": "19BBY",
        "gender": "female",
    }, {
        "name": "Owen Lars",
        "height": "178",
        "mass": "120",
        "hair_color": "brown, grey",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "52BBY",
        "gender": "male",
    }, {
        "name": "Beru Whitesun lars",
        "height": "165",
        "mass": "75",
        "hair_color": "brown",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "47BBY",
        "gender": "female",
    }, {
        "name": "R5-D4",
        "height": "97",
        "mass": "32",
        "hair_color": "n/a",
        "skin_color": "white, red",
        "eye_color": "red",
        "birth_year": "unknown",
        "gender": "n/a",
    }, {
        "name": "Biggs Darklighter",
        "height": "183",
        "mass": "84",
        "hair_color": "black",
        "skin_color": "light",
        "eye_color": "brown",
        "birth_year": "24BBY",
        "gender": "male",
    }, {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "hair_color": "auburn, white",
        "skin_color": "fair",
        "eye_color": "blue-gray",
        "birth_year": "57BBY",
        "gender": "male",
    }, {
        "name": "Anakin Skywalker",
        "height": "188",
        "mass": "84",
        "hair_color": "blond",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "41.9BBY",
        "gender": "male",
    }, {
        "name": "Wilhuff Tarkin",
        "height": "180",
        "mass": "unknown",
        "hair_color": "auburn, grey",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "64BBY",
        "gender": "male",
    }, {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "hair_color": "brown",
        "skin_color": "unknown",
        "eye_color": "blue",
        "birth_year": "200BBY",
        "gender": "male",
    }, {
        "name": "Han Solo",
        "height": "180",
        "mass": "80",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "29BBY",
        "gender": "male",
    }, {
        "name": "Greedo",
        "height": "173",
        "mass": "74",
        "hair_color": "n/a",
        "skin_color": "green",
        "eye_color": "black",
        "birth_year": "44BBY",
        "gender": "male",
    }, {
        "name": "Jabba Desilijic Tiure",
        "height": "175",
        "mass": "1,358",
        "hair_color": "n/a",
        "skin_color": "green-tan, brown",
        "eye_color": "orange",
        "birth_year": "600BBY",
        "gender": "hermaphrodite",
    }, {
        "name": "Wedge Antilles",
        "height": "170",
        "mass": "77",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "hazel",
        "birth_year": "21BBY",
        "gender": "male",
    }, {
        "name": "Jek Tono Porkins",
        "height": "180",
        "mass": "110",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "unknown",
        "gender": "male",
    }, {
        "name": "Yoda",
        "height": "66",
        "mass": "17",
        "hair_color": "white",
        "skin_color": "green",
        "eye_color": "brown",
        "birth_year": "896BBY",
        "gender": "male",
    }, {
        "name": "Palpatine",
        "height": "170",
        "mass": "75",
        "hair_color": "grey",
        "skin_color": "pale",
        "eye_color": "yellow",
        "birth_year": "82BBY",
        "gender": "male",
    }, {
        "name": "Boba Fett",
        "height": "183",
        "mass": "78.2",
        "hair_color": "black",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "31.5BBY",
        "gender": "male",
    }, {
        "name": "IG-88",
        "height": "200",
        "mass": "140",
        "hair_color": "none",
        "skin_color": "metal",
        "eye_color": "red",
        "birth_year": "15BBY",
        "gender": "none",
    }, {
        "name": "Bossk",
        "height": "190",
        "mass": "113",
        "hair_color": "none",
        "skin_color": "green",
        "eye_color": "red",
        "birth_year": "53BBY",
        "gender": "male",
    }, {
        "name": "Lando Calrissian",
        "height": "177",
        "mass": "79",
        "hair_color": "black",
        "skin_color": "dark",
        "eye_color": "brown",
        "birth_year": "31BBY",
        "gender": "male",
    }, {
        "name": "Lobot",
        "height": "175",
        "mass": "79",
        "hair_color": "none",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "37BBY",
        "gender": "male",
    }, {
        "name": "Ackbar",
        "height": "180",
        "mass": "83",
        "hair_color": "none",
        "skin_color": "brown mottle",
        "eye_color": "orange",
        "birth_year": "41BBY",
        "gender": "male",
    }, {
        "name": "Mon Mothma",
        "height": "150",
        "mass": "unknown",
        "hair_color": "auburn",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "48BBY",
        "gender": "female",
    }, {
        "name": "Arvel Crynyd",
        "height": "unknown",
        "mass": "unknown",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "unknown",
        "gender": "male",
    }, {
        "name": "Wicket Systri Warrick",
        "height": "88",
        "mass": "20",
        "hair_color": "brown",
        "skin_color": "brown",
        "eye_color": "brown",
        "birth_year": "8BBY",
        "gender": "male",
    }, {
        "name": "Nien Nunb",
        "height": "160",
        "mass": "68",
        "hair_color": "none",
        "skin_color": "grey",
        "eye_color": "black",
        "birth_year": "unknown",
        "gender": "male",
    }, {
        "name": "Shluke Skyker",
        "height": "175",
        "mass": "78",
        "hair_color": "blonda",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "19BBY",
        "gender": "male",
    }, {
        "name": "A-33P1",
        "height": "167",
        "mass": "75",
        "hair_color": "n/a",
        "skin_color": "gold",
        "eye_color": "yellow",
        "birth_year": "112BBY",
        "gender": "n/a",
    }, {
        "name": "OC4-D2",
        "height": "96",
        "mass": "32",
        "hair_color": "n/a",
        "skin_color": "white, blue",
        "eye_color": "red",
        "birth_year": "33BBY",
        "gender": "n/a",
    }, {
        "name": "Marth Vider",
        "height": "203",
        "mass": "136",
        "hair_color": "none",
        "skin_color": "black",
        "eye_color": "yellow",
        "birth_year": "41.2BBY",
        "gender": "female",
    }, {
        "name": "Leila Orna",
        "height": "10",
        "mass": "44",
        "hair_color": "brown",
        "skin_color": "light",
        "eye_color": "brown",
        "birth_year": "19BBY",
        "gender": "female",
    }, {
        "name": "Awin Lurso",
        "height": "66",
        "mass": "19",
        "hair_color": "brown, grey",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "17BBY",
        "gender": "female",
    }, {
        "name": "Seru blacksun lirs",
        "height": "65",
        "mass": "750",
        "hair_color": "brown",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "47BBY",
        "gender": "female",
    }, {
        "name": "P1-B2",
        "height": "58",
        "mass": "42",
        "hair_color": "n/a",
        "skin_color": "white, red",
        "eye_color": "red",
        "birth_year": "unknown",
        "gender": "n/a",
    }, {
        "name": "Figgs Lightlighter",
        "height": "143",
        "mass": "100",
        "hair_color": "black",
        "skin_color": "light",
        "eye_color": "brown",
        "birth_year": "274BBY",
        "gender": "male",
    }, {
        "name": "Wan Aobi",
        "height": "201",
        "mass": "121",
        "hair_color": "auburn, white",
        "skin_color": "fair",
        "eye_color": "blue-gray",
        "birth_year": "65BBY",
        "gender": "male",
    }, {
        "name": "Soki sasoki",
        "height": "192",
        "mass": "90",
        "hair_color": "blond",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "33.9BBY",
        "gender": "male",
    }, {
        "name": "Mylhuff Porkin",
        "height": "151`",
        "mass": "77",
        "hair_color": "auburn, grey",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "64BBY",
        "gender": "male",
    }, {
        "name": "Viewbocc",
        "height": "229",
        "mass": "123",
        "hair_color": "brown",
        "skin_color": "unknown",
        "eye_color": "blue",
        "birth_year": "202BBY",
        "gender": "female",
    }, {
        "name": "San Holo",
        "height": "185",
        "mass": "96",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "1BBY",
        "gender": "male",
    }, {
        "name": "Bredo",
        "height": "178",
        "mass": "70",
        "hair_color": "n/a",
        "skin_color": "green",
        "eye_color": "black",
        "birth_year": "44BBY",
        "gender": "male",
    }, {
        "name": "Jabba",
        "height": "177",
        "mass": "1358",
        "hair_color": "n/a",
        "skin_color": "green-tan, brown",
        "eye_color": "orange",
        "birth_year": "6020BBY",
        "gender": "hermaphrodite",
    }, {
        "name": "Pump Antil",
        "height": "171",
        "mass": "72",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "hazel",
        "birth_year": "23BBY",
        "gender": "male",
    }, {
        "name": "Jack Tono",
        "height": "130",
        "mass": "180",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "unknown",
        "gender": "male",
    }, {
        "name": "Moda",
        "height": "46",
        "mass": "10",
        "hair_color": "white",
        "skin_color": "green",
        "eye_color": "brown",
        "birth_year": "876BBY",
        "gender": "male",
    }, {
        "name": "Paraplone",
        "height": "210",
        "mass": "101",
        "hair_color": "grey",
        "skin_color": "pale",
        "eye_color": "yellow",
        "birth_year": "821BBY",
        "gender": "male",
    }, {
        "name": "Bob Feat",
        "height": "173",
        "mass": "75",
        "hair_color": "black",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "31.8BBY",
        "gender": "female",
    }, {
        "name": "IG-89",
        "height": "202",
        "mass": "144",
        "hair_color": "none",
        "skin_color": "metal",
        "eye_color": "red",
        "birth_year": "105BBY",
        "gender": "none",
    }, {
        "name": "Tabassk",
        "height": "191",
        "mass": "121",
        "hair_color": "none",
        "skin_color": "black",
        "eye_color": "red",
        "birth_year": "523BBY",
        "gender": "male",
    }, {
        "name": "Linda Mirinda",
        "height": "157",
        "mass": "50",
        "hair_color": "black",
        "skin_color": "dark",
        "eye_color": "brown",
        "birth_year": "31BBY",
        "gender": "female",
    }, {
        "name": "Robot Hobot",
        "height": "30",
        "mass": "14",
        "hair_color": "none",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "371BBY",
        "gender": "male",
    }, {
        "name": "Allah Babah",
        "height": "220",
        "mass": "103",
        "hair_color": "none",
        "skin_color": "brown mottle",
        "eye_color": "orange",
        "birth_year": "413BBY",
        "gender": "male",
    }, {
        "name": "Mona Liza",
        "height": "50",
        "mass": "unknown",
        "hair_color": "auburn",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "448BBY",
        "gender": "female",
    }, {
        "name": "Orwell Nyht",
        "height": "unknown",
        "mass": "unknown",
        "hair_color": "brown",
        "skin_color": "fair",
        "eye_color": "brown",
        "birth_year": "unknown",
        "gender": "male",
    }, {
        "name": "Brick Crick",
        "height": "81",
        "mass": "20",
        "hair_color": "brown",
        "skin_color": "brown",
        "eye_color": "brown",
        "birth_year": "8BBY",
        "gender": "female",
    }, {
        "name": "None Pone",
        "height": "163",
        "mass": "69",
        "hair_color": "none",
        "skin_color": "grey",
        "eye_color": "black",
        "birth_year": "unknown",
        "gender": "male",
    }];
